[phases.setup]
nixPkgs = [
  "php82",
  "php82Packages.composer",
  "php82Extensions.pdo",
  "php82Extensions.pdo_mysql",
  "php82Extensions.mbstring",
  "php82Extensions.zip",
  "php82Extensions.tokenizer",
  "php82Extensions.xml",
  "php82Extensions.curl"
]
