services:
  - type: web
    name: laravel-api
    env: php
    buildCommand: "composer install && php artisan config:cache && php artisan route:cache"
    startCommand: "php artisan serve --host=0.0.0.0 --port=$PORT"
    plan: free
    envVars:
      - key: APP_ENV
        value: production
